
// Objective-C API for talking to the following Go packages
//
//	github.com/goScrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoScrapper_FRAMEWORK_H__
#define __GoScrapper_FRAMEWORK_H__

#include "GoScrapper.objc.h"
#include "Universe.objc.h"

#endif
