// Objective-C API for talking to github.com/goScrapper Go package.
//   gobind -lang=objc github.com/goScrapper
//
// File is generated by gobind. Do not edit.

#ifndef __GoScrapper_H__
#define __GoScrapper_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GoScrapperBook;
@class GoScrapperBooks;

@interface GoScrapperBook : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull author;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull image;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) NSString* _Nonnull pdf;
@property (nonatomic) NSString* _Nonnull size;
@property (nonatomic) long pages;
@property (nonatomic) long year;
@property (nonatomic) NSString* _Nonnull isbn;
@property (nonatomic) NSString* _Nonnull category;
@property (nonatomic) NSString* _Nonnull formats;
@property (nonatomic) NSString* _Nonnull lang;
@end

@interface GoScrapperBooks : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Books.Books with unsupported type: []github.com/goScrapper.Book

// skipped method Books.AddBook with unsupported parameter or return types

@end

FOUNDATION_EXPORT NSData* _Nullable GoScrapperFetchQueueBooks(long page);

#endif
